### ISSUE TITLE
TypeScript interface

### ISSUE THREAD

**Issue by Anil8753** [kodie/md5-file#17]
Is TypeScript interface in the roadmap?

**Comment by Tzinov15** [comment]
TypeScript interface would be great to have ^^

**Comment by LinusU** [comment]
Would love this as well! PR welcome

**Comment by BamButz** [comment]
I added the definitions to https://github.com/DefinitelyTyped/DefinitelyTyped so far without promise support.

So you should get a typescript interface with "npm install @types/md5-file"
