### ISSUE TITLE
Breaking change between 4.0.0 and 5.0.0

### ISSUE THREAD

**Issue by mattbrain** [kodie/md5-file#27]
Using md5-file to md5 files with a callback on 4.0.0 works as below:

```
md5File(filename, (err, hash) => {
   console.log("starting hash on " + filename);
   if (err) {
      console.log(err);
   } else {
      console.log(hash);
   }
});
```

On 5.0.0, this no longer works, the code within the callback is never executed.

**Comment by Richienb** [comment]
@mattbrain Callback support was removed.

Try this instead:

```js
console.log("starting hash on " + filename);
md5File(filename)
	.then(hash => console.log(hash))
    .catch(error => console.log(error)
```

**Comment by LinusU** [comment]
Yes, this was intentional, please see the migration guide here: [🚢 5.0.0 / 2020-04-05](https://github.com/kodie/md5-file/releases/tag/v5.0.0)

Specifically this part:

> Instead of passing a callback to md5File, use the returned Promise e.g. by calling .then(...) on it.

So your code would be:

```js
md5File(filename).then(
  (hash) => {
    console.log("starting hash on " + filename)
    console.log(hash)
   },
  (err) => {
    console.log(err)
  }
)
```

**Comment by mattbrain** [comment]
Ah ok - I redeployed some code, in which I hadn't specified the version number for the module 
in the manifest and as a result it failed silently (in as much as the callback was never executed, but neither was any error raised). Took a little while to uncover what was going on. Would it be possible to raise an exception if the old callback approach was used?

**Comment by Richienb** [comment]
@mattbrain The whole point of a major release is for breaking changes to be introduced without worrying about backward compatibility. Therefore, raising a warning for trying to use a removed feature is probably not going to be a thing.

**Comment by LinusU** [comment]
I'm with @Richienb here, not specifying the version number in your package.json-file is a great way to have your application break in any number of ways. It's not always possible to detect all usage of old apis between breaking changes, even if in this specific instance it would probably work...

**Comment by GeekyDeaks** [comment]
I just noticed this change.  I see you had originally provided support for both callbacks and promises (which is a nice QoL feature), but it got removed very recently. 
 https://github.com/kodie/md5-file/commit/6cddc7ea8ba66b8e07ea627d91042cbd0c8c0413

Was there a technical reason to drop it?  No big deal, mostly curious to know if there was a gotcha to be aware of when adopting this approach

**Comment by Richienb** [comment]
@GeekyDeaks Callbacks are a thing of the past. If you still need to use them, try [universalify](https://github.com/RyanZim/universalify)'s fromPromise feature.

**Comment by GeekyDeaks** [comment]
yeah, totally get that @Richienb - It's more that I have to maintain code using both so I usually adopt the approach of making the APIs support both and was wondering if there was something in this approach I have overlooked that you chaps had found

**Comment by Richienb** [comment]
@GeekyDeaks Using one implementation to return a value is much easier to maintain.

**Comment by createbuildship** [comment]
the new package gives me errors:

ERROR in ./node_modules/md5-file/index.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\ct\d-claims\node_modules\md5-file'
ERROR in ./node_modules/md5-file/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\ct\d-claims\node_modules\md5-file'

**Comment by LinusU** [comment]
@frontr-uk are you running this under Node.js? The `crypto` and `fs` modules should be built in...

**Comment by LinusU** [comment]
@frontr-uk are you running this under Node.js? The `crypto` and `fs` modules should be built in...
